language: node_js
node_js:
- 14.17.5
cache: npm

install:
  - npm install
directories:
  - node_modules
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: main