language: node_js
node_js:
- 14.17.5
cache: npm

install:
  - npm install
directories:
  - node_modules
before_script:
  - export NODE_OPTIONS=--max_old_space_size=8192
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: gh-pages